### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/CO_FallenEagle.Tembelan#1]
- [x] schwebende Objekte am Zielgebäude löschen, sobald es einstürzt
- [x] sicherstellen, dass Zielgebäude kaputtgeht
- [x] Teleport am Start
- [x] Loadpic
- [x] Intro
- [x] Spawnbasis verschönern
- [x] Uhrzeit und Wetter
- [x] extra Ausdauer für HAT?
- [x] Speedboote bei Exfil
- [x] [Intel Texte](https://github.com/gruppe-adler/CO_FallenEagle.Tembelan/blob/master/USER/functions/fn_intelInteractionServer.sqf#L20) hinzufügen
- [x] ~~Outro?~~
- [x] Briefing aus Thread in Mission übertragen
- [x] ~~zerstörte Gebäude Modul buggy~~
- [x] Flugschreibermodell ändern
- [x] skiptime checken
- [x] replay
- [x] freezes bei tp
- [x] feindl. Einheiten
- [x] groupsettings, radiosettings
- [x] loadouts checken
- [x] Briefing Bildschirm
